# Generated by Django 4.2.5 on 2023-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleprovince',
            name='city_code',
            field=models.CharField(default='', help_text='城市简称', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='city_id',
            field=models.CharField(blank=True, default='', help_text='城市代码', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='city_name',
            field=models.CharField(default='', help_text='城市名称', max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='code_id',
            field=models.CharField(blank=True, default='', help_text='分类编号', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='province_code',
            field=models.CharField(default='', help_text='省份简称', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='province_id',
            field=models.CharField(blank=True, default='', help_text='省份代码', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprovince',
            name='province_name',
            field=models.CharField(default='', help_text='省份名称', max_length=120),
        ),
    ]
