# Generated by Django 4.2.7 on 2023-11-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain_in', '0003_alter_vehicleprovince_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitionvarieties',
            name='AV_name',
            field=models.CharField(default='', help_text='收购品种', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='acquisitionvarieties',
            name='acquisitioncaps',
            field=models.DecimalField(decimal_places=4, help_text='收购上限', max_digits=16),
        ),
        migrations.AlterField(
            model_name='gbcorninformations',
            name='acquisitionVarietiesid',
            field=models.CharField(blank=True, default='', help_text='收购品种', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moistureprice',
            name='purchase_id',
            field=models.CharField(blank=True, default='', help_text='等级标准', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moistureprice',
            name='varieties_id',
            field=models.CharField(blank=True, default='', help_text='品种名称', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualityinspectiondeductionstandard',
            name='file_id',
            field=models.CharField(blank=True, default='', help_text='对应质检文件ID号', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unloadingfee',
            name='varieties_id',
            field=models.CharField(blank=True, default='', help_text='品种名称', max_length=50, null=True),
        ),
    ]
