# Generated by Django 4.2.7 on 2023-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain_in', '0004_alter_acquisitionvarieties_av_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityinspectiondeductionstandardback',
            name='deduction_ratio',
            field=models.DecimalField(decimal_places=2, help_text='扣减比例%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='qualityinspectiondeductionstandardback',
            name='increment_scale',
            field=models.DecimalField(decimal_places=2, help_text='增量比例%', max_digits=10),
        ),
    ]
