# Generated by Django 4.2.5 on 2023-11-17 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabasePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='127.0.0.1', help_text='数据库连接地址', max_length=255)),
                ('port', models.CharField(default='3306', help_text='数据库端口号', max_length=255)),
                ('db_name', models.CharField(default='xyms_db', help_text='数据库名', max_length=255)),
                ('user_name', models.CharField(default='root', help_text='用户名', max_length=255)),
                ('password', models.CharField(default='', help_text='密码', max_length=255)),
                ('charset', models.CharField(default='utf-8', help_text='字符编码', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_name', models.CharField(default='', help_text='企业名称', max_length=255, unique=True)),
                ('enter_uncode', models.CharField(default='', help_text='统一代码证号', max_length=255)),
                ('enter_author_start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='授权开始时间')),
                ('enter_author_end_date', models.DateTimeField(default=django.utils.timezone.now, help_text='授权开始时间')),
                ('enter_code', models.CharField(default='', help_text='企业码', max_length=255)),
                ('enter_author_code', models.CharField(default='', help_text='授权码', max_length=255)),
                ('enter_free_credit', models.IntegerField(default=50, help_text='授权额度')),
                ('version_number', models.CharField(default='', help_text='版本号', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProgectPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_name', models.CharField(default='', help_text='程序工作目录', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_datetime', models.DateField(default=datetime.datetime.now, help_text='系统执行时间')),
                ('real_datetime', models.DateTimeField(auto_now=True, help_text='真实时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_name', models.CharField(help_text='权限名称', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='pbkdf2_sha256$600000$980513$AkfU8AiPz1H+nbPiK0qdc8doPY55C65ziluYKU5pAHE=', help_text='用户名', max_length=255, unique=True)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$1975217$cIG/fgs++BsR52DfcPKvrRRTVa/Z4/bvITlUlwxGdgM=', help_text='登录密码', max_length=255)),
                ('show_name', models.CharField(default='鑫奕科创', help_text='用来显示用户名信息', max_length=255)),
                ('user_permissions', models.ForeignKey(help_text='用户权限', on_delete=django.db.models.deletion.CASCADE, related_name='userpremissions', to='login.userpermissions')),
            ],
        ),
    ]
