# Generated by Django 4.2.7 on 2023-12-05 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_local',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_local',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$1975217$cIG/fgs++BsR52DfcPKvrRRTVa/Z4/bvITlUlwxGdgM=', help_text='登录密码', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_local',
            name='show_name',
            field=models.CharField(blank=True, default='鑫奕科创', help_text='用来显示用户名信息', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_local',
            name='username',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$980513$AkfU8AiPz1H+nbPiK0qdc8doPY55C65ziluYKU5pAHE=', help_text='用户名', max_length=50, null=True, unique=True),
        ),
    ]
