# Generated by Django 4.2.7 on 2023-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasepath',
            name='charset',
            field=models.CharField(blank=True, default='utf-8', help_text='字符编码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='db_name',
            field=models.CharField(blank=True, default='xyms_db', help_text='数据库名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='host',
            field=models.CharField(blank=True, default='127.0.0.1', help_text='数据库连接地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='password',
            field=models.CharField(blank=True, default='', help_text='密码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='port',
            field=models.CharField(blank=True, default='3306', help_text='数据库端口号', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='user_name',
            field=models.CharField(blank=True, default='root', help_text='用户名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_author_code',
            field=models.CharField(blank=True, default='', help_text='授权码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_author_end_date',
            field=models.DateTimeField(blank=True, help_text='授权开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_author_start_date',
            field=models.DateTimeField(blank=True, help_text='授权开始时间', null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_code',
            field=models.CharField(blank=True, default='', help_text='企业码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_free_credit',
            field=models.IntegerField(blank=True, default=50, help_text='授权额度', null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enter_uncode',
            field=models.CharField(blank=True, default='', help_text='统一代码证号', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='version_number',
            field=models.CharField(blank=True, default='', help_text='版本号', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='progectpath',
            name='path_name',
            field=models.CharField(blank=True, default='', help_text='程序工作目录', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$1975217$cIG/fgs++BsR52DfcPKvrRRTVa/Z4/bvITlUlwxGdgM=', help_text='登录密码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='show_name',
            field=models.CharField(blank=True, default='鑫奕科创', help_text='用来显示用户名信息', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.CharField(blank=True, default='游客', help_text='用户权限', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$980513$AkfU8AiPz1H+nbPiK0qdc8doPY55C65ziluYKU5pAHE=', help_text='用户名', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='permissions_name',
            field=models.CharField(blank=True, help_text='权限名称', max_length=255, null=True, unique=True),
        ),
    ]
