# Generated by Django 4.2.7 on 2023-11-20 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_databasepath_charset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundate',
            name='run_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='系统执行时间'),
        ),
    ]
