# Generated by Django 4.2.7 on 2023-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_local_create_datetime_alter_user_local_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_local',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$1975217$cIG/fgs++BsR52DfcPKvrRRTVa/Z4/bvITlUlwxGdgM=', help_text='登录密码', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_local',
            name='username',
            field=models.CharField(blank=True, default='pbkdf2_sha256$600000$980513$AkfU8AiPz1H+nbPiK0qdc8doPY55C65ziluYKU5pAHE=', help_text='用户名', max_length=255, null=True, unique=True),
        ),
    ]
