# Generated by Django 4.2.7 on 2023-11-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_rundate_run_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundate',
            name='real_datetime',
            field=models.DateTimeField(auto_now=True, help_text='本机时间'),
        ),
        migrations.AlterField(
            model_name='rundate',
            name='run_datetime',
            field=models.DateTimeField(help_text='系统执行时间'),
        ),
    ]
