# Generated by Django 4.2.7 on 2023-12-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_local_password_alter_user_local_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logs',
            name='login_user_code',
            field=models.CharField(blank=True, default='', help_text='登录的企业code', max_length=100, null=True),
        ),
    ]
