# Generated by Django 4.2.7 on 2023-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_rundate_real_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissions',
            name='premissions_code',
            field=models.CharField(blank=True, default='', help_text='权限ID', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='permissions_name',
            field=models.CharField(blank=True, default='', help_text='权限名称', max_length=255, null=True, unique=True),
        ),
    ]
