# Generated by Django 4.2.7 on 2023-12-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_login_logs_login_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_logs',
            name='login_enter_code',
            field=models.CharField(blank=True, default='', help_text='登录的企业code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login_logs',
            name='login_user_code',
            field=models.CharField(blank=True, default='<empty>', help_text='登录的用户code', max_length=100, null=True),
        ),
    ]
