# Generated by Django 4.2.7 on 2023-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_login_logs_login_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_logs',
            name='logout_time',
            field=models.DateTimeField(blank=True, help_text='登出时间', null=True),
        ),
    ]
