# Generated by Django 4.2.7 on 2023-12-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_login_logs_logout_time'),
        ('login', '0006_login_logs_login_dev_uuid_and_more'),
    ]

    operations = [
    ]
