# Generated by Django 4.2.7 on 2023-11-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_premissions_code_userpermissions_permissions_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='pbkdf2_sha256$600000$980513$AkfU8AiPz1H+nbPiK0qdc8doPY55C65ziluYKU5pAHE=', help_text='用户名', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='pbkdf2_sha256$600000$1975217$cIG/fgs++BsR52DfcPKvrRRTVa/Z4/bvITlUlwxGdgM=', help_text='登录密码', max_length=255, null=True)),
                ('show_name', models.CharField(blank=True, default='鑫奕科创', help_text='用来显示用户名信息', max_length=255, null=True)),
                ('user_permissions', models.CharField(blank=True, default='0000', help_text='用户权限', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
