# Generated by Django 4.2.7 on 2023-12-28 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_merge_20231228_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_logs',
            name='login_user_id',
        ),
        migrations.AlterField(
            model_name='login_logs',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='最后操作或者登出时间'),
        ),
    ]
