# Generated by Django 4.2.7 on 2023-11-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_user_local_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progectpath',
            old_name='path_name',
            new_name='projectfile_path',
        ),
        migrations.AddField(
            model_name='progectpath',
            name='profiles_path',
            field=models.CharField(blank=True, default='', help_text='配置文件目录', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='progectpath',
            name='reportfile_path',
            field=models.CharField(blank=True, default='', help_text='报表文件目录', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='progectpath',
            name='resourcefile_path',
            field=models.CharField(blank=True, default='', help_text='资源文件目录', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='progectpath',
            name='tempfiles_path',
            field=models.CharField(blank=True, default='', help_text='临时文件目录', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='databasepath',
            name='password',
            field=models.CharField(blank=True, default='53169549', help_text='密码', max_length=255, null=True),
        ),
    ]
