# Generated by Django 4.2.7 on 2023-12-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_login_logs_login_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_local',
            name='enter_name',
        ),
        migrations.AddField(
            model_name='user_local',
            name='enter_code',
            field=models.CharField(blank=True, default='', help_text='账户所属企业code', max_length=255, null=True),
        ),
    ]
