# Generated by Django 4.2.7 on 2023-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_path_name_progectpath_projectfile_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='app_name',
            field=models.CharField(blank=True, default='', help_text='授权使用软件名称', max_length=255, null=True),
        ),
    ]
