# Generated by Django 4.2.7 on 2024-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_user_local_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_local',
            name='user_email',
            field=models.CharField(blank=True, default='xykc@xy2cn.cn', help_text='用户电子信箱', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_local',
            name='user_phone',
            field=models.CharField(blank=True, default='15145181511', help_text='用户电话', max_length=30, null=True),
        ),
    ]
