#DEFINE HKEY_CLASSES_ROOT 2147483648 && 0x80000000，或用负数: -2147483648
#DEFINE HKEY_CURRENT_USER 2147483649 && 0x80000001，-2147483647
HKEY_LOCAL_MACHINE=2147483650 && 0x80000002，-2147483646
#DEFINE HKEY_USERS 2147483651 && 0x80000003，-2147483645
#DEFINE HKEY_PERFORMANCE_DATA 2147483652 && 0x80000004，-2147483644
#DEFINE HKEY_CURRENT_CONFIG 2147483653 && 0x80000005，-2147483643
#DEFINE HKEY_DYN_DATA 2147483654 && 0x80000006，-2147483642
SET DATE TO LONG
SET CENTURY ON
SET NOTIFY OFF
SET TALK OFF
PUBLIC MAINPATH,SERVERPATH,DLLPATH,REPORTPATH,PROJECTPATH,TOOLSPATH,LOGSPATH,LOCALUUID,SURL,RETUUID
PUBLIC ENTER_NAME,ENTER_UNCODE,ENTER_START,ENTER_END,ENTER_FREE,VERSION_NUM,APP_NAME
MAINPATH=ALLTRIM(SYS(5)+SYS(2003))+'\'
SERVERPATH=MAINPATH+'xymsdb\'
LOGSPATH=MAINPATH+'logs\'
DLLPATH=MAINPATH+'dll\'
REPORTPATH=MAINPATH+'report\'
PROJECTPATH=MAINPATH+'prg\'
TOOLSPATH=MAINPATH+'tools\'
SERVERURL='http://127.0.0.1'
SERVERPORT=':8000'
SURL=SERVERURL+SERVERPORT+'/'
SET LIBRARY TO DLLPATH+'xyms_f.FLL'
LOCALUUID=GETGUID(3)
IF FCREATE("ss.dll")<=0
	=MESSAGEBOX("程序已经启动，请检查任务栏是否存在程序图标！",0,"禁止多开提示信息")
	QUIT
ENDIF
VRET=HTTPPOSTDATA(SURL+'test/','test')
IF VRET=='ok' THEN
	SET LIBRARY TO DLLPATH+'xyms_f.fLL'
	=INIWRITE(TTOC(DATETIME()),LOCALUUID,'AppLogin',LOGSPATH+'xyms_log.log')
	SET LIBRARY TO DLLPATH+'xyms_j.dll'
	JSON=JSON_CREATE()
	JSON_APPEND(JSON,JSON_CREATE(LOCALUUID),'uuid')
	JSON_DATA=JSON_TOSTRING(JSON)
	SET LIBRARY TO DLLPATH+'xyms_f.fLL'
	VRET=HTTPPOSTDATA(SURL+'login/get_enterprise_information/',JSON_DATA)
	SET LIBRARY TO DLLPATH+'xyms_j.dll'
	RETU_VRET=JSON_PARSE(VRET)
	IF JSON_CHILDS(RETU_VRET)>0 THEN
		FOR X=1 TO JSON_CHILDS(RETU_VRET) STEP 1
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'retuuid') TO RETUUID
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'enter_name') TO ENTER_NAME
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'enter_uncode') TO ENTER_UNCODE
			STORE CTOT(STRCONV(JSON_VALUE(JSON_VALUE(RETU_VRET,X),'enter_author_start_date'),11)) TO ENTER_START
			STORE CTOT(STRCONV(JSON_VALUE(JSON_VALUE(RETU_VRET,X),'enter_author_end_date'),11)) TO ENTER_END
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'enter_free_credit') TO ENTER_FREE
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'version_number') TO VERSION_NUM
			STORE JSON_VALUE(JSON_VALUE(RETU_VRET,X),'app_name') TO APP_NAME
		ENDFOR
		MODI WINDOW SCREEN  NOCLOSE NOFLOAT NOGROW TITLE APP_NAME+SPACE(5)+"登录时间："+DTOC(DATETIME())+TIME()
		ZOOM WIND SCREEN MAX
		SET LIBRARY TO DLLPATH+'xyms_f.fLL'
		XYINI=MAINPATH+'\xy.ini'
		QQQ=INIREAD('主窗口背景图片',"default",'窗口背景',XYINI)
		IF !FILE(QQQ)
			QQQ=MAINPATH+'\media\背景图片\psb.jpg'
		ENDIF
		BGPCI=INIREAD('子窗口背景图片',"default",'窗口背景',XYINI)
		IF !FILE(BGPCI)
			BGPCI=MAINPATH+'\media\背景图片\风景04.jpg'
		ENDIF
		TB=INIREAD('窗口图标',"default",'窗口背景',XYINI)
		IF !FILE(TB)
			TB=MAINPATH+'\media\tb.ico'
		ENDIF
		_SCREEN.ADDOBJECT("IMG","Image")
		_SCREEN.LOCKSCREEN=.F.
		_SCREEN.IMG.TOP=0
		_SCREEN.IMG.LEFT=0
		_SCREEN.IMG.WIDTH=_SCREEN.WIDTH
		_SCREEN.IMG.HEIGHT=_SCREEN.HEIGHT
		_SCREEN.IMG.VISIBLE=.T.
		SETDESKTOP=2
		_SCREEN.IMG.STRETCH=SETDESKTOP     &&SetDesktop:0   ,1-居中     2-拉伸
		_SCREEN.IMG.PICTURE=QQQ
		_SCREEN.ICON=TB
		DO FORM 'LOGIN'
		DO 'workbar'
		READ EVEN
	ELSE
		=MESSAGEBOX('软件未完成企业注册，请向软件供应商索取企业注册资料或者退出停止使用本软件！',0,'系统提示')
		DO MAINPATH+'\menu\regmenu.MPR'
	ENDIF
ELSE
	=MESSAGEBOX('内网服务器未启动，请检查各启动项是否运行正常！',0,'服务启动异常提示')
	QUIT
ENDIF
