#DEFINE HKEY_CLASSES_ROOT 2147483648 && 0x80000000，或用负数: -2147483648
#DEFINE HKEY_CURRENT_USER 2147483649 && 0x80000001，-2147483647
HKEY_LOCAL_MACHINE=2147483650 && 0x80000002，-2147483646
#DEFINE HKEY_USERS 2147483651 && 0x80000003，-2147483645
#DEFINE HKEY_PERFORMANCE_DATA 2147483652 && 0x80000004，-2147483644
#DEFINE HKEY_CURRENT_CONFIG 2147483653 && 0x80000005，-2147483643
#DEFINE HKEY_DYN_DATA 2147483654 && 0x80000006，-2147483642
SET DATE TO LONG
SET CENTURY ON
SET NOTIFY OFF
SET TALK OFF
PUBLIC MAINPATH,SERVERPATH,DLLPATH,REPORTPATH,PROJECTPATH,TOOLSPATH,LOGSPAHT,LOCALUUID
MAINPATH=ALLTRIM(SYS(5)+SYS(2003))+'\'
SERVERPATH=MAINPATH+'xymsdb\'
LOGSPATH=MAINPATH+'logs\'
DLLPATH=MAINPATH+'dll\'
REPORTPATH=MAINPATH+'report\'
PROJECTPATH=MAINPATH+'prg\'
TOOLSPATH=MAINPATH+'tools\'
SERVERURL='http://127.0.0.1'
SERVERPORT=':8000'
SURL=SERVERURL+SERVERPORT+'/'
SET LIBRARY TO DLLPATH+'xyms_f.FLL'
LOCALUUID=GETGUID(3)
IF FCREATE("ss.dll")<=0
	=MESSAGEBOX("程序已经启动，请检查任务栏是否存在程序图标！",0,"禁止多开提示信息")
	QUIT
ENDIF
VRET=HTTPPOSTDATA(SURL+'test/','test')
IF VRET=='ok' THEN
	SET LIBRARY TO DLLPATH+'xyms_f.FLL'
	=INIWRITE(TTOC(DATETIME()),LOCALUUID,'AppLogin',LOGSPATH+'xyms_log.log')
	SET LIBRARY TO DLLPATH+'xyms_j.dll'
	JSON=JSON_CREATE()
	JSON.APPEND(JSON,JSON_CREATE('uuid'),LOCALUUID)
	JSON_DATA=JSON_TOSTRING(JSON)
	VRET=HTTPPOSTDATA(SURL+'login/get_enterprise_information/',JSON_DATA)

	MODI WINDOW SCREEN  NOCLOSE NOFLOAT NOGROW TITLE "鑫奕软件--粮食企业进销存管理系统(单机版)"+SPACE(5)+"登录时间："+DTOC(DATETIME())+TIME()
	ZOOM WIND SCREEN MAX
	XYINI=MAINPATH+'\xy.ini'
	QQQ=INIREAD('主窗口背景图片',"default",'窗口背景',XYINI)
	IF !FILE(QQQ)
		QQQ=MAINPATH+'\media\背景图片\psb.jpg'
	ENDIF
	BGPCI=INIREAD('子窗口背景图片',"default",'窗口背景',XYINI)
	IF !FILE(BGPCI)
		BGPCI=MAINPATH+'\media\背景图片\风景04.jpg'
	ENDIF
	TB=INIREAD('窗口图标',"default",'窗口背景',XYINI)
	IF !FILE(TB)
		TB=MAINPATH+'\media\tb.ico'
	ENDIF
	_SCREEN.ADDOBJECT("IMG","Image")
	_SCREEN.LOCKSCREEN=.F.
	_SCREEN.IMG.TOP=0
	_SCREEN.IMG.LEFT=0
	_SCREEN.IMG.WIDTH=_SCREEN.WIDTH
	_SCREEN.IMG.HEIGHT=_SCREEN.HEIGHT
	_SCREEN.IMG.VISIBLE=.T.
	SETDESKTOP=2
	_SCREEN.IMG.STRETCH=SETDESKTOP     &&SetDesktop:0   ,1-居中     2-拉伸
	_SCREEN.IMG.PICTURE=QQQ
	_SCREEN.ICON=TB
	SELECT COUNT(*) INTO ARRAY A1 FROM YHDBF
	SELECT * FROM HQR INTO CURSOR HQRTMP
	STORE ALLTRIM(HQRTMP.HQRNAME) TO HQRMC
	DO WORKBAR
	IF SQRQ_1<DATE() THEN
		DO MAINPATH+'\menu\regmenu.MPR'
	ELSE
		IF A1>0 THEN
			TI=MESSAGEBOX('当前系统日期为：'+DTOC(DATE()),4+16,'系统日期提醒')
			IF TI=6
				DO FORM MAINPATH+"\SCX\LOGIN"
			ELSE
				DO FORM MAINPATH+"\SCX\settime"
			ENDIF
		ELSE
			DO MAINPATH+"\menu\mainm.MPR"
		ENDIF
	ENDIF
	READ EVEN


ELSE
	=MESSAGEBOX('内网服务器未启动，请检查各启动项是否运行正常！',0,'服务启动异常提示')
	QUIT
ENDIF
